"""SO(3) and pose geometry utilities extracted from the notebook."""

from .posterior_core import (
    Pose,
    ensure_vector,
    ensure_matrix,
    hat,
    vee,
    exp_so3,
    log_so3,
    project_to_so3,
    right_plus_pose,
    pose_inverse,
    compose_pose,
    skew,
    so3_exp,
    adjoint_wrench_transform,
    nominal_AB_transform,
    make_rotation_y,
    make_rotation_z,
    hat3,
    exp_so3_local,
    right_retract_pose_local,
    angle_between,
)
from .sampling_core import geodesic_distance_so3, axis_angle_to_rot, quat_to_rot

__all__ = [
    "Pose",
    "ensure_vector",
    "ensure_matrix",
    "hat",
    "vee",
    "exp_so3",
    "log_so3",
    "project_to_so3",
    "right_plus_pose",
    "pose_inverse",
    "compose_pose",
    "skew",
    "so3_exp",
    "adjoint_wrench_transform",
    "nominal_AB_transform",
    "make_rotation_y",
    "make_rotation_z",
    "hat3",
    "exp_so3_local",
    "right_retract_pose_local",
    "angle_between",
    "geodesic_distance_so3",
    "axis_angle_to_rot",
    "quat_to_rot",
]
